version: 2020-05-13
project: "beacon-v2"
paths:
  out: "../schemas"
  schemafile: "../../specification-v2/beacon.yaml"
  headerfile: "../source/header.yaml"
header:
  "$schema": http://json-schema.org/draft-07/schema#
  "$id": https://beacon-project.io/schemas/__project__/__schema__/__version__
  meta:
    contributors:
      - description: ELIXIR Beacon team
        id: "https://beacon-project.io/categories/people.html"
      - description: Sabela de la Torre Pernas
        id: __contributor_ORCID__
      - description: Sabela de la Torre Pernas
        id: __contributor_ORCID__
      - description: Michael Baudis
        id: ORCID:0000-0002-9903-4248
    provenance:
      - description: Beacon v2 draft schema
        id: https://github.com/ga4gh-beacon/specification-v2
    used_by:
      - description: Beacon, for Beacon v2 testing
        id: https://github.com/ga4gh-beacon/specification-v2
    sb_status: playground
